name: Idea
description: Something the DevReply web SDK should do.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What you or your users are trying to do.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would help
