// Builds src/icons.ts from the iOS and Android artwork, so all three SDKs share the same icons.
// Run: node scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const ios = '../swift/Sources/DevReply/Resources/Icons.xcassets'
const android = '../android/devreply/src/main/res/drawable'
const svg = (p) => readFileSync(p, 'utf8').trim().replace(/\s*\n\s*/g, ' ')

// Material Symbols vector drawables → 24×24 SVG with currentColor.
const vector = (name) => {
  const xml = readFileSync(`${android}/${name}.xml`, 'utf8')
  // Filled paths take the colour as fill; stroked ones (close, send) as stroke, with their width and caps.
  const paths = [...xml.matchAll(/<path([^>]+)\/>/g)].map(([, attrs]) => {
    const get = (name) => new RegExp(`android:${name}="([^"]+)"`).exec(attrs)?.[1]
    const d = get('pathData')
    if (!get('strokeColor')) return `<path d="${d}"/>`
    const cap = get('strokeLineCap') ?? 'butt'
    const join = get('strokeLineJoin') ?? 'miter'
    return `<path d="${d}" fill="none" stroke="currentColor" stroke-width="${get('strokeWidth') ?? 2}" stroke-linecap="${cap}" stroke-linejoin="${join}"/>`
  })
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">${paths.join('')}</svg>`
}

const icons = {
  bug: svg(`${ios}/devreply-bug.imageset/bug.svg`),
  billing: svg(`${ios}/devreply-billing.imageset/billing.svg`),
  idea: svg(`${ios}/devreply-idea.imageset/idea.svg`),
  question: svg(`${ios}/devreply-question.imageset/question.svg`),
  other: svg(`${ios}/devreply-other.imageset/other.svg`),
  mark: svg(`${ios}/devreply-mark.imageset/mark.svg`),
  attach: vector('devreply_ic_attach'),
  back: vector('devreply_ic_back'),
  close: vector('devreply_ic_close'),
  file: vector('devreply_ic_file'),
  photo: vector('devreply_ic_photo'),
  send: vector('devreply_ic_send'),
  warning: vector('devreply_ic_warning'),
  arrow: vector('devreply_ic_arrow_right'),
}

const out = `// Generated by scripts/gen-icons.mjs from the iOS and Android artwork. Don't edit by hand.
export const icons = ${JSON.stringify(icons, null, 2)} as const

export type IconName = keyof typeof icons
`
writeFileSync('src/icons.ts', out)
console.log('icons:', Object.keys(icons).join(', '))
